return {
  ["Docker"] = "󰡨",
  ["Docker Desktop"] = "󰡨",
  ["Finder"] = "󰀶",
  ["Spotify"] = "",
  ["Default"] = ":default:",
  ["App Store"] = "",
  ["Warp"] = "",
  ["System Settings"] = "",
  ["Google Chrome"] = "",
  ["Code"] = "󰨞",
  ["Numbers"] = "",
  ["Terminal"] = "",
  ["Slack"] = "󰒱",
  ["Preview"] = "󰈦",
  ["Firefox"] = "󰈹",
  ["Zen Browser"] = "󰈹",
  ["Zen"] = "󰈹",
  ["Beekeeper Studio"] = "",
  ["Yaak"] = "󰡷",
  ["AWS VPN Client"] = "󰌾",
  ["QGIS"] = "󰮪",
  ["qgis"] = "󰮪",
  ["Ghostty"] = "󰊠",
  ["Font Book"] = "󰛖",
  ["Activity Monitor"] = "",
  ["default"] = "󰣆",
}
